### ISSUE TITLE
可否支持一下加载本地图片？

### ISSUE THREAD

**Issue by idootop** [lf7817/taro-qm-poster#1]

**Comment by lf7817** [comment]
wxfile://开头的吗

**Comment by idootop** [comment]
> wxfile://开头的吗

两种，一种是wxfile://  一种是项目内部的assets

**Comment by lf7817** [comment]
wxfile:// 可以支持，另外一种是不支持的，放cdn上吧

**Comment by lf7817** [comment]
wxfile已支持，升级到1.5.0

**Comment by idootop** [comment]
> wxfile:// 可以支持，另外一种是不支持的，放oss上吧

ok，晓得了

**Comment by idootop** [comment]
> wxfile已支持，升级到1.5.0

多谢！

**Comment by lf7817** [comment]
此仓库不维护了，请使用[taro-poster-render](https://github.com/lf7817/taro-poster-render)
